name: Build OC Patch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run build script
    -  run: |
      chmod 755 scripts/build.sh
      scripts/build.sh
